package org.example.model.manytomany;

public class SQLCode3 {
    //create table Actor(
    //    id int generated by default as identity primary key,
    //    name varchar(100) not null unique,
    //    age int check (age > 0)
    //);
    //
    //create table Movie(
    //    id int generated by default as identity primary key,
    //    name varchar(200) not null,
    //    year int check (year > 1900)
    //);
    //
    //create table Actor_Movie(
    //    actor_id int references Actor(id),
    //    movie_id int references Movie(id),
    //    primary key(actor_id, movie_id)
    //);
}
